name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: master  # or the branch you want to sync

    - name: Setup Git
      run: |
        git config --global user.email "1258956799@qq.com"
        git config --global user.name "zhangdi"

    - name: Sync
      run: |
        git remote add upstream https://github.com/qdleader/qdleader.git
        git fetch upstream
        git pull --rebase=interactive upstream master
        git push https://${{ secrets.GH_TOKEN }}@github.com/fuguid/Front-end-interview-questions.git HEAD:master || exit 0
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
