name: Sync Fork

on:
  schedule:
    # - cron: '0 0 * * *'  # Runs every day at midnight

     - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master  # or the branch you want to sync

    - name: Setup Git
      run: |
        git config --global user.email "1258956799@qq.com"
        git config --global user.name "zhangdi"

    - name: Sync
      run: |
        git remote add upstream https://github.com/qdleader/qdleader.git
        git fetch upstream
        git pull --rebase upstream master
        git push
